// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTEScholarshipSystem.Models;

#nullable disable

namespace UTEScholarshipSystem.Migrations
{
    [DbContext(typeof(ScholarshipDbContext))]
    [Migration("20250530173101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UTEScholarshipSystem.Models.Scholarship", b =>
                {
                    b.Property<int>("ScholarshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalRequirements")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ApplicationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ApplicationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MinGPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScholarshipId");

                    b.ToTable("Scholarships");

                    b.HasData(
                        new
                        {
                            ScholarshipId = 1,
                            AcademicYear = 2024,
                            Amount = 2000000m,
                            ApplicationEndDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicationStartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(2382),
                            Description = "Học bổng dành cho sinh viên có kết quả học tập xuất sắc",
                            MinGPA = 3.2m,
                            Name = "Học bổng Khuyến khích học tập",
                            Quantity = 50,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(2804)
                        },
                        new
                        {
                            ScholarshipId = 2,
                            AcademicYear = 2024,
                            AdditionalRequirements = "Có giấy xác nhận hộ nghèo hoặc cận nghèo",
                            Amount = 1500000m,
                            ApplicationEndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicationStartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(3676),
                            Description = "Học bổng dành cho sinh viên có hoàn cảnh khó khăn",
                            MinGPA = 2.5m,
                            Name = "Học bổng Hỗ trợ sinh viên khó khăn",
                            Quantity = 100,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(3678)
                        },
                        new
                        {
                            ScholarshipId = 3,
                            AcademicYear = 2024,
                            AdditionalRequirements = "Có giải thưởng cấp quốc gia hoặc quốc tế",
                            Amount = 5000000m,
                            ApplicationEndDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApplicationStartDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(3691),
                            Description = "Học bổng dành cho sinh viên có tài năng đặc biệt",
                            MinGPA = 3.7m,
                            Name = "Học bổng Tài năng",
                            Quantity = 10,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 662, DateTimeKind.Local).AddTicks(3692)
                        });
                });

            modelBuilder.Entity("UTEScholarshipSystem.Models.ScholarshipApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("Achievements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyEconomicStatus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GPAAtApplication")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("StudentId", "ScholarshipId")
                        .IsUnique();

                    b.ToTable("ScholarshipApplications");
                });

            modelBuilder.Entity("UTEScholarshipSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            AcademicYear = 2021,
                            Address = "123 Võ Văn Ngân, Thủ Đức, TP.HCM",
                            Class = "ĐHCNTT21A",
                            CreatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 664, DateTimeKind.Local).AddTicks(4109),
                            DateOfBirth = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "20110001@student.hcmute.edu.vn",
                            FullName = "Nguyễn Văn An",
                            GPA = 3.5m,
                            Major = "Công nghệ thông tin",
                            PhoneNumber = "0123456789",
                            StudentCode = "20110001",
                            UpdatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 664, DateTimeKind.Local).AddTicks(4591)
                        },
                        new
                        {
                            StudentId = 2,
                            AcademicYear = 2021,
                            Address = "456 Nguyễn Văn Cừ, Quận 5, TP.HCM",
                            Class = "ĐHKĐT21B",
                            CreatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 664, DateTimeKind.Local).AddTicks(5077),
                            DateOfBirth = new DateTime(2003, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "20110002@student.hcmute.edu.vn",
                            FullName = "Trần Thị Bình",
                            GPA = 3.8m,
                            Major = "Kỹ thuật điện tử",
                            PhoneNumber = "0987654321",
                            StudentCode = "20110002",
                            UpdatedAt = new DateTime(2025, 5, 31, 0, 31, 0, 664, DateTimeKind.Local).AddTicks(5079)
                        });
                });

            modelBuilder.Entity("UTEScholarshipSystem.Models.ScholarshipApplication", b =>
                {
                    b.HasOne("UTEScholarshipSystem.Models.Scholarship", "Scholarship")
                        .WithMany("ScholarshipApplications")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTEScholarshipSystem.Models.Student", "Student")
                        .WithMany("ScholarshipApplications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UTEScholarshipSystem.Models.Scholarship", b =>
                {
                    b.Navigation("ScholarshipApplications");
                });

            modelBuilder.Entity("UTEScholarshipSystem.Models.Student", b =>
                {
                    b.Navigation("ScholarshipApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
